function createView( obj , parent )
    obj.Parent = parent;

    this_dir = fileparts( mfilename( 'fullpath' ) );
    icon_dir = fullfile( this_dir,'..','..','Resources' );

    obj.Container = uipanel('Parent',obj.Parent,...
        'Title',obj.Title,...
        'BorderType',obj.BorderType,...
        'Units', obj.Units,...
        'Position',obj.Position);
    set(obj.Parent,'ResizeFcn',@obj.resize);

    posCont = getpixelposition(obj.Container);

    %% Scattered Gains Group
    obj.GainSelectionPanel = uipanel('Parent',obj.Container,...
        'Units','Pixels',...
        'Position', [ 1 , posCont(4) - 110 , 330 , 110 ]);

    % Scattered Gains Label
    obj.ScatterLabelComp = uilabel(obj.GainSelectionPanel,...
        'Text','Scattered Gains',...
        'BackgroundColor',[55 96 146]/255,...
        'FontName','Courier New',...
        'FontColor','w');
    obj.ScatterLabelCont = obj.ScatterLabelComp;

    % Scattered Gain File Object
    obj.ScattFileName = uilabel(obj.GainSelectionPanel,...
        'Text','Scattered Gain Collection:',...
        'HorizontalAlignment','left',...
        'FontName','Courier New');

    obj.HCompScatGainFile = uidropdown(obj.GainSelectionPanel,...
        'Items',{' '},...
        'Editable','on',...
        'Tooltip','Scattered Gain Object',...
        'ValueChangedFcn',@obj.scattGainFileSel_CB);
    obj.HContScatGainFile = obj.HCompScatGainFile;

    % Select Scattered Gain
    obj.TextGainName = uilabel(obj.GainSelectionPanel,...
        'Text','Select Scattered Gain:',...
        'HorizontalAlignment','left',...
        'FontName','Courier New');

    obj.HCompGainSel = uidropdown(obj.GainSelectionPanel,...
        'Items',{' '},...
        'Editable','on',...
        'Tooltip','Select the Gain',...
        'ValueChangedFcn',@obj.gainSel_CB);
    obj.HContGainSel = obj.HCompGainSel;

    % Independent Variable
    obj.IndVarText = uilabel(obj.GainSelectionPanel,...
        'Text','Independent Variable:',...
        'HorizontalAlignment','left',...
        'FontName','Courier New');

    obj.HCompIndVar = uidropdown(obj.GainSelectionPanel,...
        'Items',{' '},...
        'Editable','on',...
        'Tooltip','Select the Independant Variable',...
        'ValueChangedFcn',@obj.indVar_CB);
    obj.HContIndVar = obj.HCompIndVar;

    % Edit Buttons
    obj.EditGainListButtonHComp = uibutton(obj.GainSelectionPanel,...
        'Text','Edit',...
        'ButtonPushedFcn',@obj.updateSelectableScatteredGains);
    obj.EditGainListJButtonHCont = obj.EditGainListButtonHComp;

    obj.EditIndVarListButtonHComp = uibutton(obj.GainSelectionPanel,...
        'Text','Edit',...
        'ButtonPushedFcn',@obj.updateSelectableIndependantVars);
    obj.EditIndVarListJButtonHCont = obj.EditIndVarListButtonHComp;

    %% Scheduled Gains Group
    obj.GainSchedulePanel = uipanel('Parent',obj.Container,...
        'Units','Pixels',...
        'Position', [ 1 , posCont(4) - 320 , 330 , 200 ]);

    obj.SchLabelComp = uilabel(obj.GainSchedulePanel,...
        'Text','Scheduled Gains',...
        'BackgroundColor',[55 96 146]/255,...
        'FontName','Courier New',...
        'FontColor','w');
    obj.SchLabelCont = obj.SchLabelComp;

    obj.SchFileName = uilabel(obj.GainSchedulePanel,...
        'Text','Scheduled Gain Collection:',...
        'HorizontalAlignment','left',...
        'FontName','Courier New');

    obj.HCompSelSchFile = uidropdown(obj.GainSchedulePanel,...
        'Items',{'Add New ...'},...
        'Tooltip','Scheduled Gain File',...
        'ValueChangedFcn',@obj.schGainFileSel_CB);
    obj.HContSelSchFileFile = obj.HCompSelSchFile;

    obj.NewSchJButtonHComp = uibutton(obj.GainSchedulePanel,...
        'Text','Add',...
        'ButtonPushedFcn',@obj.newSchedule_CB);
    obj.NewSchJButtonHCont = obj.NewSchJButtonHComp;

    obj.RemoveSchCollJButtonHComp = uibutton(obj.GainSchedulePanel,...
        'Text','Remove',...
        'ButtonPushedFcn',@obj.removeSchedule_CB);
    obj.RemoveSchCollJButtonHCont = obj.RemoveSchCollJButtonHComp;

    obj.ExportSchJButtonHComp = uibutton(obj.GainSchedulePanel,...
        'Text','Export',...
        'ButtonPushedFcn',@obj.exportSchedule_CB);
    obj.ExportSchJButtonHCont = obj.ExportSchJButtonHComp;

    obj.SchGainName = uilabel(obj.GainSchedulePanel,...
        'Text','Scheduled Gain Name:',...
        'HorizontalAlignment','left',...
        'FontName','Courier New');

    obj.HCompSchGainName = uidropdown(obj.GainSchedulePanel,...
        'Items',{' '},...
        'Editable','on',...
        'Tooltip','Scheduled Gain Name',...
        'ValueChangedFcn',@obj.schGainNameSel_CB);
    obj.HContSchGainName = obj.HCompSchGainName;
    if isempty(obj.ScheduledGainNamesArray)
        obj.HCompSchGainName.Items = {' '};
    else
        obj.HCompSchGainName.Items = obj.ScheduledGainNamesArray;
    end

    obj.NewSchGainNameJButtonHComp = uibutton(obj.GainSchedulePanel,...
        'Text','Add',...
        'ButtonPushedFcn',@obj.newSchGainName_CB);
    obj.NewSchGainNameJButtonHCont = obj.NewSchGainNameJButtonHComp;

    obj.RemoveSchGainNameJButtonHComp = uibutton(obj.GainSchedulePanel,...
        'Text','Remove',...
        'ButtonPushedFcn',@obj.rmScheduleGainName_CB);
    obj.RemoveSchGainNameJButtonHCont = obj.RemoveSchGainNameJButtonHComp;

    obj.TextDimension = uilabel(obj.GainSchedulePanel,...
        'Text','Dimension:',...
        'HorizontalAlignment','left',...
        'FontName','Courier New');


    obj.HContTableDim = uidropdown(obj.GainSchedulePanel,...
        'Items',obj.TableDimList,...
        'Value',obj.TableDimList{obj.SelectedTableDimension},...
        'ValueChangedFcn',@obj.tableDim_CB);

    obj.TextBP1Name = uilabel(obj.GainSchedulePanel,...
        'Text','Break Points 1 Name:',...
        'HorizontalAlignment','left',...
        'FontName','Courier New');

    obj.BP1Name_eb = uieditfield(obj.GainSchedulePanel,'text',...
        'Value', obj.BreakPoints1TableName,...
        'ValueChangedFcn',@obj.bp1TableName_CB);

    obj.TextBP2Name = uilabel(obj.GainSchedulePanel,...
        'Text','Break Points 2 Name:',...
        'HorizontalAlignment','left',...
        'FontName','Courier New');
    obj.TextBP2NameCont = obj.TextBP2Name;

    obj.BP2Name_eb = uieditfield(obj.GainSchedulePanel,'text',...
        'Value', obj.BreakPoints2TableName,...
        'ValueChangedFcn',@obj.bp2TableName_CB);

    obj.TextBP1Value = uilabel(obj.GainSchedulePanel,...
        'Text','Break Points 1 Value:',...
        'HorizontalAlignment','left',...
        'FontName','Courier New');
    obj.TextBP1ValueCont = obj.TextBP1Value;

    obj.BP1ValueString_eb = uieditfield(obj.GainSchedulePanel,'text',...
        'Value', obj.BP1ValueString,...
        'ValueChangedFcn',@obj.bp1Value_CB);

    obj.TextBP = uilabel(obj.GainSchedulePanel,...
        'Text','Break Points 2 Values:',...
        'HorizontalAlignment','left',...
        'FontName','Courier New');
    obj.TextBPCont = obj.TextBP;

    obj.BP_eb = uieditfield(obj.GainSchedulePanel,'text',...
        'Value', obj.BreakPointsString,...
        'ValueChangedFcn',@obj.bp_CB);

    %% Gain Fit
    obj.GainFittingPanel = uipanel('Parent',obj.Container);

    obj.GainFitLabelComp = uilabel(obj.GainFittingPanel,...
        'Text','Gain Fit',...
        'BackgroundColor',[55 96 146]/255,...
        'FontName','Courier New',...
        'FontColor','w');
    obj.GainFitLabelCont = obj.GainFitLabelComp;

    obj.PolyFitTable = uitable('Parent',obj.GainFittingPanel,...
        'ColumnName',{'Polynomial Order','Fitting Range'},...
        'RowName',[],...
        'ColumnEditable', [true,true],...
        'ColumnFormat',{'char', 'char'},...
        'ColumnWidth',{100,200},...
        'Data',obj.PolyFitData,...
        'CellEditCallback', @obj.polyTable_ce_CB,...
        'CellSelectionCallback', @obj.polyTable_cs_CB);

    obj.SchJButtonHComp = uibutton(obj.GainFittingPanel,...
        'Text','Schedule',...
        'ButtonPushedFcn',@obj.schedule_CB);
    obj.SchJButtonHCont = obj.SchJButtonHComp;

    obj.RemoveSchJButtonHComp = uibutton(obj.GainFittingPanel,...
        'Text','Clear Plot',...
        'ButtonPushedFcn',@obj.removeSch_CB);
    obj.RemoveSchJButtonHCont = obj.RemoveSchJButtonHComp;

    %% Options
    obj.OptionsPanel = uipanel('Parent',obj.Container);

    obj.OptionsLabelComp = uilabel(obj.OptionsPanel,...
        'Text','Options',...
        'BackgroundColor',[55 96 146]/255,...
        'FontName','Courier New',...
        'FontColor','w');
    obj.OptionsLabelCont = obj.OptionsLabelComp;

    obj.JTable = uitable('Parent',obj.OptionsPanel,...
        'Data',cell(5,5),...
        'ColumnName',{' ',' ',' ',' ',' '},...
        'ColumnEditable',true(1,5),...
        'CellEditCallback',@obj.dataUpdatedInTable,...
        'CellSelectionCallback',@obj.mousePressedInTable);
    obj.HContainer = obj.JTable;

    obj.ViewTableJButtonHComp = uibutton(obj.OptionsPanel,...
        'Text','Plot Table',...
        'ButtonPushedFcn',@obj.viewTable_CB);
    obj.ViewTableJButtonHCont = obj.ViewTableJButtonHComp;

    obj.RemoveRowJButtonHComp = uibutton(obj.OptionsPanel,...
        'Text','Remove',...
        'ButtonPushedFcn',@obj.removeRowGainTable);
    obj.RemoveRowJButtonHCont = obj.RemoveRowJButtonHComp;

    obj.ExportTableJButtonHComp = uibutton(obj.OptionsPanel,...
        'Text','Export Table',...
        'ButtonPushedFcn',@obj.exportTable_CB);
    obj.ExportTableJButtonHCont = obj.ExportTableJButtonHComp;

    %% Axis
    obj.GainSchAxisColl = UserInterface.AxisPanelCollection('Parent',obj.Container,'NumOfPages',1,'NumOfAxisPerPage',1);
    for i = 0:obj.GainSchAxisColl.AxisHandleQueue.size-1
        set(obj.GainSchAxisColl.AxisHandleQueue.get(i),'Visible','on');
    end

    %% Update
    updateTable( obj );
    setScatteredGainFileComboBox( obj );
    setGainSelectionComboBox( obj );
    setIndVarComboBox( obj );
    setSchGainFileComboBox( obj );
    update( obj );

    resize( obj , [] , [] );
end % createView
