%function [hdl] = FilterParam2Gui(hdl)
import FilterDesign.*
hdl = maintemp;

% Get Design Parameter Data
[Param] = NotchFilterParam();

% Number of Parameters
nParam  = size(Param.Data,1);

% Label ------- Value --------- Min ------- Slider --------- Max
for i = 1:nParam
    VarName = Param.Data{i,1};
    VarLabel= Param.Data{i,2};
    
    VarMin  = Param.Data{i,3};
    VarMax  = Param.Data{i,4};
    
    StructName = Param.Label;
    
    eval(['hdl.data.' StructName 'Settings.' VarName '_Max = VarMax;']);
    eval(['hdl.data.' StructName 'Settings.' VarName '_Min = VarMin;']);
    
    eval(['hdl.gui.DesignParam' StructName 'St' VarName '= uicontrol(''Parent'',hdl.gui.panelDesignParamNotch,'...
        '''Style'',''text'','...
        '''String'',''' VarLabel ''','...
        '''FontSize'',9,'...
        '''FontName'',''Calibri'','...
        '''Units'',''normalized'','...
        '''Position'',[.05,' num2str(0.75-0.15*(i-1)) ',.4,.1]'','...
        '''HorizontalAlignment'',''Left'');']);
    
    eval(['hdl.gui.DesignParam' StructName 'Et' VarName '= uicontrol(''Parent'',hdl.gui.panelDesignParamNotch,'...
        '''Style'',''edit'','...
        '''FontSize'',9,'...
        '''BackGroundColor'',''w'','...
        '''FontName'',''Calibri'','...
        '''Units'',''normalized'','...
        '''Position'',[.4,' num2str(0.76-0.15*(i-1)) ',.1,.1]'','...
        '''HorizontalAlignment'',''Left'','...
        '''CallBack'',{@et_getDpVals_Callback});']);
    
    eval(['hdl.gui.DesignParam' StructName 'Et' VarName 'Min= uicontrol(''Parent'',hdl.gui.panelDesignParamNotch,'...
        '''Style'',''edit'','...
        '''FontSize'',9,'...
        '''BackGroundColor'',''w'','...
        '''FontName'',''Calibri'','...
        '''Units'',''normalized'','...
        '''Position'',[.525,' num2str(0.76-0.15*(i-1)) ',.075,.1]'','...
        '''HorizontalAlignment'',''Center'','...
        '''CallBack'',{@etDpMinMax_CallBack});']);
    
    eval(['hdl.gui.DesignParam' StructName 'Et' VarName 'Max= uicontrol(''Parent'',hdl.gui.panelDesignParamNotch,'...
        '''Style'',''edit'','...
        '''FontSize'',9,'...
        '''BackGroundColor'',''w'','...
        '''FontName'',''Calibri'','...
        '''Units'',''normalized'','...
        '''Position'',[.85,' num2str(0.76-0.15*(i-1)) ',.075,.1]'','...
        '''HorizontalAlignment'',''Center'','...
        '''CallBack'',{@etDpMinMax_CallBack});']);
    
    eval(['hdl.gui.DesignParam' StructName 'Sl' VarName '= uicontrol(''Parent'',hdl.gui.panelDesignParamNotch,'...
        '''Style'',''slider'','...
        '''FontSize'',9,'...
        '''BackGroundColor'',''w'','...
        '''FontName'',''Calibri'','...
        '''Units'',''normalized'','...
        '''Position'',[.61,' num2str(0.76-0.15*(i-1)) ',.23,.1]'','...
        '''CallBack'',{@sl_Sliders_Callback});']);
    
    
end

