function main(parent)
import FilterDesign.*
%--------------------------------------------------------------------------
%        MAIN:   FILTER DESIGN TOOL
%     COMPANY:   AEROSPACE CONTROL DYNAMICS, LLC.
%--------------------------------------------------------------------------
%        DATE:   09-26-2014
%      AUTHOR:   NOMAAN SAEED
%     VERSION:   1.0
%--------------------------------------------------------------------------
% DESCRIPTION:   THIS IS THE MAIN GRAPHICAL USER INTERFACE FUNCTION WHICH
%                ALLOWS USERS TO DESIGN ANY FILTERS
%--------------------------------------------------------------------------

%% DETECT SCREENSIZE AND POSITION MAIN FIGURE
%--------------------------------------------------------------------------
scrsz = get(0,'ScreenSize');
width =  0.6*1920;
height = 0.7*1020;
posw = width/scrsz(3);
posh = height/scrsz(4);

if nargin == 0
% Launch main figure window
    hdl.gui.mainFig = figure('Visible','on',...
        'units','normalized',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'Position',[(1-posw)/2 (1-posh)/2 posw posh],...
        'Resize','off',...
        'Name','AEROSPACE CONTROL DYNAMICS, LLC');

set(hdl.gui.mainFig,'Units','Pixels');

elseif nargin == 1
    
    hdl.gui.mainFig = parent;
else
    error('Too many input arguments.');
end
%% DEFINE MAJOR PANELS
%--------------------------------------------------------------------------
hdl.gui.panelMain = uipanel('parent',hdl.gui.mainFig,...
    'Position',[0.0,0.0,1,1]);

% Define all panels
hdl.gui.panelTitle   = uipanel('parent',hdl.gui.mainFig,...
    'Position',[0.01,0.89,0.4,0.1],...
    'BackGroundColor','w');
hdl.gui.panelFilterType  = uipanel('parent',hdl.gui.mainFig,....
    'Position',[0.01,0.78,0.4,0.1]);
hdl.gui.panelFilters = uipanel('parent',hdl.gui.mainFig,...
    'Position',[0.01,0.47,0.4,0.3]);
hdl.gui.panelDesignParam  = uipanel('parent',hdl.gui.mainFig,....
    'Position',[0.01,0.09,0.4,0.375]);
hdl.gui.panelControls= uipanel('parent',hdl.gui.mainFig,...
    'Position',[0.01,0.01,0.4,0.075]);
hdl.gui.panelPlot= uipanel('parent',hdl.gui.mainFig,...
    'Position',[0.415,0.01,0.57,0.98]);

%% DEFINE TITLE PANEL
%--------------------------------------------------------------------------
hdl.gui.panelTitleSt = uicontrol(...
    'Parent',hdl.gui.panelTitle,...
    'Style','text',...
    'String',{'FILTER DESIGN'},...
    'FontSize',16,...
    'FontWeight','bold',...
    'BackGroundColor','w',...
    'ForegroundColor',[0.1,0.3,0.5],...
    'FontName','Times New Roman',...
    'Units','normalized',...
    'Position',[.5,0.2,.5,.5],...
    'HorizontalAlignment','Left');

%% ACD LOGO
%--------------------------------------------------------------------------
acdlogo = axes(...
    'Parent',hdl.gui.panelTitle,...
    'Position',[0 0.075 0.4 0.9]);
this_dir = fileparts( mfilename( 'fullpath' ) );
icon_dir = fullfile( this_dir,'..','+UserInterface','Resources' );

acdlogo = imread(fullfile(icon_dir,'Aerospace_Control_Dynamics_LOGO.jpg'));
image(acdlogo);
axis('equal')
axis('off')

%% FILTER TYPE PANEL
%--------------------------------------------------------------------------
hdl.gui.panelFilterTypeStType = uicontrol(...
    'Parent',hdl.gui.panelFilterType,...
    'Style','text',...
    'String',{'Select Filter Type'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.4,.4,.5],...
    'HorizontalAlignment','Left');
hdl.gui.panelFilterTypePmType = uicontrol(...
    'Parent',hdl.gui.panelFilterType,...
    'Style','popup',...
    'String',{'Notch/BandPass Filter','Lead/Lag Filter','Complimentary Filter'},...
    'FontSize',9,...
    'BackGroundColor','w',...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.1,.3,.5],...
    'CallBack',{@pm_FilterType_Callback});

hdl.gui.panelFilterTypeStFilterOrder = uicontrol(...
    'Parent',hdl.gui.panelFilterType,...
    'Style','text',...
    'String',{'Order'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.375,0.4,.4,.5],...
    'HorizontalAlignment','Left',...
    'Enable','off');
hdl.gui.panelFilterTypePmFilterOrder = uicontrol(...
    'Parent',hdl.gui.panelFilterType,...
    'Style','popup',...
    'BackGroundColor','w',...
    'String',{1,2},...
    'FontSize',9,...
    'Value',2,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.375,0.25,.1,.35],...
    'Enable','off',...
    'CallBack',{@pm_FilterOrder_Callback});

hdl.gui.panelFilterTypeStName = uicontrol(...
    'Parent',hdl.gui.panelFilterType,...
    'Style','text',...
    'String',{'Name'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.5,0.4,.4,.5],...
    'HorizontalAlignment','Left');
hdl.gui.panelFilterTypeEtName = uicontrol(...
    'Parent',hdl.gui.panelFilterType,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[.5,0.25,.3,.35],...
    'CallBack',{@et_FilterName_Callback});

hdl.gui.panelFilterTypePbAdd = uicontrol(...
    'Parent',hdl.gui.panelFilterType,...
    'Style','push',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'String','Add',...
    'HorizontalAlignment','Left',...
    'Position',[.825,0.25,.15,.35],...
    'CallBack',{@pb_FilterAdd_Callback});

%% FILTERS PANEL
%--------------------------------------------------------------------------
hdl.gui.panelFiltersStListBox = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','text',...
    'String',{'Plot Filters'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.4,.4,.5],...
    'HorizontalAlignment','Left');

hdl.gui.panelFiltersListBox = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','listbox',...
    'FontSize',9,...
    'FontName','Calibri',...
    'BackGroundColor','w',...
    'Units','normalized',...
    'Max',10,...
    'Min',1,...
    'Value',1,...
    'Position',[.05,0.2,.4,.6],...
    'HorizontalAlignment','Left',...
    'CallBack',{@lb_FilterListBox_Callback});

hdl.gui.panelFiltersPbDelete = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','push',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'String','Delete',...
    'HorizontalAlignment','Left',...
    'Position',[.05,0.05,.15,.125],...
    'CallBack',{@pb_FilterDelete_Callback});

hdl.gui.panelFiltersStPlotType = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','text',...
    'String',{'Plot Type:'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.55,0.8,.2,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelFiltersPmPlotType = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','popupmenu',...
    'String',{'Bode','Nichols','P-Z Map'},...
    'FontSize',9,...
    'FontName','Calibri',...
    'BackGroundColor','w',...
    'Units','normalized',...
    'Position',[.55,.7,.175,.125],...
    'HorizontalAlignment','Left',...
    'CallBack',{@Pm_PlotType_CallBack});

hdl.gui.panelFiltersStFreqUnits = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','text',...
    'String',{'Freq Units:'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.75,0.8,.2,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelFiltersPmFreqUnits = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','popupmenu',...
    'String',{'Hz','rad/s'},...
    'FontSize',9,...
    'FontName','Calibri',...
    'BackGroundColor','w',...
    'Units','normalized',...
    'Position',[.75,.7,.175,.125],...
    'HorizontalAlignment','Left',...
    'CallBack',{@Pm_FreqUnits_CallBack});

hdl.gui.panelFiltersStFreqPts = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','text',...
    'String',{'Frequency Points (Hz):'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.55,0.575,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelFiltersEtFreqPts = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','edit',...
    'String','logspace(-2,2,10000)',...
    'FontSize',9,...
    'FontName','Calibri',...
    'BackGroundColor','w',...
    'Units','normalized',...
    'Position',[.55,.475,.375,.125],...
    'HorizontalAlignment','Left',...
    'CallBack',{@pb_PlotFilter_CallBack});

hdl.gui.panelFiltersStGainLim = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','text',...
    'String',{'Gain Lim:'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.55,0.35,.2,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelFiltersEtGainLim = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','edit',...
    'String','auto',...
    'FontSize',9,...
    'FontName','Calibri',...
    'BackGroundColor','w',...
    'Units','normalized',...
    'Position',[.55,.25,.175,.125],...
    'HorizontalAlignment','Left',...
    'CallBack',{@pb_PlotFilter_CallBack});

hdl.gui.panelFiltersStFreqMax = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','text',...
    'String',{'Max Freq:'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.55,0.35,.2,.1],...
    'HorizontalAlignment','Left',...
    'Visible','off');

hdl.gui.panelFiltersEtFreqMax = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','edit',...
    'String','auto',...
    'FontSize',9,...
    'FontName','Calibri',...
    'BackGroundColor','w',...
    'Units','normalized',...
    'Position',[.55,.25,.175,.125],...
    'HorizontalAlignment','Left',...
    'Visible','off',...
    'CallBack',{@pb_PlotFilter_CallBack});

hdl.gui.panelFiltersStPhaseLim = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','text',...
    'String',{'Phase Lim:'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.75,0.35,.2,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelFiltersEtPhaseLim = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','edit',...
    'String','auto',...
    'FontSize',9,...
    'FontName','Calibri',...
    'BackGroundColor','w',...
    'Units','normalized',...
    'Position',[.75,.25,.175,.125],...
    'HorizontalAlignment','Left',...
    'CallBack',{@pb_PlotFilter_CallBack});

hdl.gui.panelFiltersCBFilterInfo = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','checkbox',...
    'String','Filter Info',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.55,.025,.25,.125],...
    'HorizontalAlignment','Left',...
    'CallBack',{@cb_FilterInfo_CallBack});

hdl.gui.panelPlotOptionsStAddDispData = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','text',...
    'String',{'Display Freq:'},...
    'FontWeight','bold',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.75,.10,.25,.125],...
    'HorizontalAlignment','Left');


% hdl.gui.panelPlotOptionsStAddDispFreq = uicontrol(...
%     'Parent',hdl.gui.panelFilters,...
%     'Style','text',...
%     'String',{'(Hz)'},...
%     'FontSize',9,...
%     'FontName','Calibri',...
%     'Units','normalized',...
%     'Position',[.93,.00,.07,.125],...
%     'HorizontalAlignment','Left');

 
hdl.gui.panelPlotOptionsEtAddDispFreq = uicontrol(...
    'Parent',hdl.gui.panelFilters,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.75,.025,.175,.125],...
    'HorizontalAlignment','Left',...
    'Enable','on',...
    'CallBack',{@et_AddPts_CallBack});

%% NOTCH FILTER DESIGN PARAMETERS PANEL
%--------------------------------------------------------------------------
hdl.gui.panelDesignParamNotch  = uipanel('parent',hdl.gui.panelDesignParam,....
    'Position',[0.0,0.05,1.0,0.8],...
    'BorderType','none',...
    'Visible','on');

% Design Parameter Labels and Values
hdl.gui.panelDesignParametersStDp = uicontrol(...
    'Parent',hdl.gui.panelDesignParam,...
    'Style','text',...
    'String','Filter Parameters:',...
    'FontSize',11,...
    'FontWeight','bold',...
    'FontName','Calibri',...
    'Units','pixels',...%''Units','normalized',...
    'Position',[23.90 , 225 , 183.20 , 12.65],...%'Position',[.05,0.95,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelFiltersPMList = uicontrol(...
    'Parent',hdl.gui.panelDesignParam,...
    'Style','popup',...
    'FontSize',9,...
    'FontName','Calibri',...
    'BackGroundColor','w',...
    'Units','pixels',...%'Units','normalized',...
    'String',{''},...
    'Position',[184.20 , 225  , 91.60 , 21.30],...%'Position',[.40,1,.2,.08],...
    'HorizontalAlignment','Left',...
    'CallBack',{@pm_FilterListBox_Callback});

hdl.gui.panelDesignParamStCurVal = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','text',...
    'String','Value',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.35,0.87,.2,.075],...
    'HorizontalAlignment','Center');

hdl.gui.panelDesignParamStSlMinDp = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','text',...
    'String','Min',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.87,.075,.075],...
    'HorizontalAlignment','Center');

hdl.gui.panelDesignParamStSlMaxDp = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','text',...
    'String','Max',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.87,.075,.075],...
    'HorizontalAlignment','Center');

hdl.gui.panelDesignParamNotchStDpCenterFreq = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','text',...
    'String','Center Frequency (Hz):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.75,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamNotchEtDpCenterFreq = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.76,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

hdl.gui.panelDesignParamNotchStDpCenterAttn = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','text',...
    'String','Center Attenuation (dB):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.6,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamNotchEtDpCenterAttn = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.61,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

hdl.gui.panelDesignParamNotchStDpFreq2 = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','text',...
    'String','2nd Frequency (Hz):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.45,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamNotchEtDpFreq2 = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.46,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

hdl.gui.panelDesignParamNotchStDpAttn2 = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','text',...
    'String','2nd Attenuation (dB):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.30,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamNotchEtDpAttn2 = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.31,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

hdl.gui.panelDesignParamNotchStDpDCGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','text',...
    'String','DC Gain (dB):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.15,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamNotchEtDpDCGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.16,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

hdl.gui.panelDesignParamNotchStDpHFGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','text',...
    'String','HF Gain (dB):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.0,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamNotchEtDpHFGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.01,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

% Slider Current Value and Min/Max

hdl.gui.panelDesignParamNotchSlMinDpCenterFreq = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.76,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamNotchSlMaxDpCenterFreq = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.76,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamNotchSlMinDpCenterAttn = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'FontSize',9,...
    'BackGroundColor','w',...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.61,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamNotchSlMaxDpCenterAttn = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.61,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamNotchSlMinDpFreq2 = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.46,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamNotchSlMaxDpFreq2 = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.46,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamNotchSlMinDpAttn2 = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.31,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamNotchSlMaxDpAttn2 = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.31,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamNotchSlMinDpDCGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.16,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamNotchSlMaxDpDCGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.16,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamNotchSlMinDpHFGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.01,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamNotchSlMaxDpHFGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.01,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

% Sliders
hdl.gui.panelDesignParamNotchSlDpCenterFreq = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.76,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamNotchSlDpCenterAttn = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.61,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamNotchSlDpFreq2 = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.46,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamNotchSlDpAttn2 = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.31,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamNotchSlDpDCGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.16,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamNotchSlDpHFGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamNotch,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.01,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

%% LEAD/LAG FILTER 1st ORDER
hdl.gui.panelDesignParamLLFirstOrder  = uipanel('parent',hdl.gui.panelDesignParam,....
    'Position',[0.0,0.1,1.0,0.8],...
    'BorderType','none',...
    'Visible','off');

hdl.gui.panelDesignParamLLFirstOrderStDpFreq = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','text',...
    'String','Frequency (Hz):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.75,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamLLFirstOrderEtDpFreq = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.76,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

hdl.gui.panelDesignParamLLFirstOrderStDpPhase = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','text',...
    'String','Phase (deg):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.6,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamLLFirstOrderEtDpPhase = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.61,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

hdl.gui.panelDesignParamLLFirstOrderStGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','text',...
    'String','Gain (dB):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.45,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamLLFirstOrderEtDpGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.46,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});


% Slider Current Value and Min/Max

hdl.gui.panelDesignParamLLFirstOrderSlMinDpFreq = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.76,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamLLFirstOrderSlMaxDpFreq = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.76,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamLLFirstOrderSlMinDpPhase = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','edit',...
    'FontSize',9,...
    'BackGroundColor','w',...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.61,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamLLFirstOrderSlMaxDpPhase = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.61,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamLLFirstOrderSlMinDpGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.46,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamLLFirstOrderSlMaxDpGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.46,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamLLFirstOrderCBMaxPhase = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','checkbox',...
    'String','Max/Min Phase',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.29,.4,.1],...
    'HorizontalAlignment','Left',...
    'CallBack',{@cb_MaxPhase_CallBack});

% Sliders
hdl.gui.panelDesignParamLLFirstOrderSlDpFreq = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.76,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamLLFirstOrderSlDpPhase = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.61,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamLLFirstOrderSlDpGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLFirstOrder,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.46,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

%% LEAD/LAG FILTER 2nd ORDER
hdl.gui.panelDesignParamLLSecondOrder  = uipanel('parent',hdl.gui.panelDesignParam,....
    'Position',[0.0,0.1,1.0,0.8],...
    'BorderType','none',...
    'Visible','off');

hdl.gui.panelDesignParamLLSecondOrderStDpFreqPMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','text',...
    'String','Freq @ Max Phase (Hz):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.75,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamLLSecondOrderEtDpFreqPMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.76,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

hdl.gui.panelDesignParamLLSecondOrderStDpPhaseMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','text',...
    'String','Max Phase (deg):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.6,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamLLSecondOrderEtDpPhaseMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.61,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

hdl.gui.panelDesignParamLLSecondOrderStHFGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','text',...
    'String','HF Gain (dB):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.45,.4,.1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamLLSecondOrderEtDpHFGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.46,.1,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@et_getDpVals_Callback});

hdl.gui.panelDesignParamLLSecondOrderStDpFreqGMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','text',...
    'String','Freq @ Max Gain (Hz):',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.10,.4,.1],...
    'Enable','on',...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamLLSecondOrderEtDpFreqGMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.4,0.11,.1,.1],...
    'HorizontalAlignment','Center',...
    'Enable','on',...
    'CallBack',{@et_getDpVals_Callback});


% Slider Current Value and Min/Max

hdl.gui.panelDesignParamLLSecondOrderSlMinDpFreqPMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.76,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamLLSecondOrderSlMaxDpFreqPMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.76,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamLLSecondOrderSlMinDpPhaseMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'FontSize',9,...
    'BackGroundColor','w',...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.61,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamLLSecondOrderSlMaxDpPhaseMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.61,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamLLSecondOrderSlMinDpHFGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.46,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamLLSecondOrderSlMaxDpHFGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.46,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

hdl.gui.panelDesignParamLLSecondOrderSlMinDpFreqGMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.525,0.11,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});
hdl.gui.panelDesignParamLLSecondOrderSlMaxDpFreqGMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','edit',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.85,0.11,.075,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@etDpMinMax_CallBack});

% Sliders
hdl.gui.panelDesignParamLLSecondOrderSlDpFreqPMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.76,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamLLSecondOrderSlDpPhaseMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.61,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamLLSecondOrderSlDpHFGain = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.46,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamLLSecondOrderSlDpFreqGMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Style','slider',...
    'BackGroundColor','w',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.61,0.11,.23,.1],...
    'HorizontalAlignment','Center',...
    'CallBack',{@sl_Sliders_Callback});

hdl.gui.panelDesignParamLLSecondOrderUIBGroup = uibuttongroup(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrder,...
    'Position',[.05,0.25,.875,.15],...
    'BorderType','none',...
    'SelectionChangeFcn',@selcb_LLSecondOrderUIBGroup);

hdl.gui.panelDesignParamLLSecondOrderRBFreqGMax = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrderUIBGroup,...
    'Style','radiobutton',...
    'String','Specify Freq @ Max Gain',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.0,0.0,0.5,1],...
    'HorizontalAlignment','Left');

hdl.gui.panelDesignParamLLSecondOrderRBPhasePos = uicontrol(...
    'Parent',hdl.gui.panelDesignParamLLSecondOrderUIBGroup,...
    'Style','radiobutton',...
    'String','Phase Positive for all Freqs',...
    'FontSize',9,...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.5,0.0,0.5,1],...
    'HorizontalAlignment','Left');

%% CONTROLS PANEL
%--------------------------------------------------------------------------
hdl.gui.panelControlsPbPlot= uicontrol(...
    'Parent',hdl.gui.panelControls,...
    'Style','push',...
    'FontSize',9,...
    'String','Plot',...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.05,0.2,.23,.5],...
    'HorizontalAlignment','Center',...
    'Enable','on',...
    'CallBack',{@pb_PlotFilter_CallBack});

hdl.gui.panelControlsPbExport= uicontrol(...
    'Parent',hdl.gui.panelControls,...
    'Style','push',...
    'FontSize',9,...
    'String','Export',...
    'FontName','Calibri',...
    'Units','normalized',...
    'Position',[.3,0.2,.23,.5],...
    'HorizontalAlignment','Center',...
    'Enable','on',...
    'CallBack',{@pb_ExportFilter_CallBack});

%% PLOT PANEL BODE
%--------------------------------------------------------------------------
hdl.gui.panelPlotBode= uipanel('parent',hdl.gui.panelPlot,...
    'Position',[0.0,0.0,1,1],...
    'BorderType','none',...
    'Visible','on');

hdl.gui.BodeGainAxes =subplot(2,1,1,'Parent',hdl.gui.panelPlotBode);
hdl.gui.BodePhaseAxes =subplot(2,1,2,'Parent',hdl.gui.panelPlotBode);


%% PLOT PANEL NICHOLS
hdl.gui.panelPlotNichols= uipanel('parent',hdl.gui.panelPlot,...
    'Position',[0.0,0.0,1,1],...
    'BorderType','none',...
    'Visible','off');

hdl.gui.NicholsAxes = subplot(1,1,1,'Parent',hdl.gui.panelPlotNichols);

%% PLOT PANEL PZMAP
hdl.gui.panelPlotPZMap= uipanel('parent',hdl.gui.panelPlot,...
    'Position',[0.0,0.0,1,1],...
    'BorderType','none',...
    'Visible','off');

hdl.gui.PZMapAxes = subplot(1,1,1,'Parent',hdl.gui.panelPlotPZMap);



%% INITIALIZA GUI
%--------------------------------------------------------------------------
initgui;
[hdl] = initFilter(hdl);

%% CALLBACKS
%--------------------------------------------------------------------------
    function pm_FilterType_Callback(~,~)
        import FilterDesign.*
        iFilterType = get(hdl.gui.panelFilterTypePmType,'Value');
        FilterTypes   = get(hdl.gui.panelFilterTypePmType,'string');
        SelFilterType = FilterTypes{iFilterType};
        
        if strcmp(SelFilterType,'Notch/BandPass Filter')
            set(hdl.gui.panelFilterTypeStFilterOrder,'Enable','off');
            set(hdl.gui.panelFilterTypePmFilterOrder,'Enable','off');
            set(hdl.gui.panelFilterTypePmFilterOrder,'Value',2);
            FilterOrder = get(hdl.gui.panelFilterTypePmFilterOrder,'value');
            hdl.data.FilterOrder = FilterOrder;
        elseif strcmp(SelFilterType,'Lead/Lag Filter');
            set(hdl.gui.panelFilterTypeStFilterOrder,'Enable','on');
            set(hdl.gui.panelFilterTypePmFilterOrder,'Enable','on');
            set(hdl.gui.panelFilterTypePmFilterOrder,'Value',1);
            FilterOrder = get(hdl.gui.panelFilterTypePmFilterOrder,'value');
            hdl.data.FilterOrder = FilterOrder;
        else
            errordlg('Only Notch/BandPass Filters are supported.');
            iFilterType = 1;
            SelFilterType = 'Notch/BandPass Filter';
            set(hdl.gui.panelFilterTypePmType,'Value',iFilterType);
            %             set(hdl.gui.panelFilterTypeStOrder,'Enable','on');
            %             set(hdl.gui.panelFilterTypeEtOrder,'Enable','on');
        end
        
        hdl.data.iFilterType   = iFilterType;
        hdl.data.selFilterType = SelFilterType;
    end % End Callback

    function pm_FilterOrder_Callback(~,~)
        import FilterDesign.*
        FilterOrder = get(hdl.gui.panelFilterTypePmFilterOrder,'value');
        hdl.data.FilterOrder = FilterOrder;
    end % End Callback

    function et_FilterName_Callback(~,~)
        import FilterDesign.*
        FilterName = get(hdl.gui.panelFilterTypeEtName,'String');
        hdl.data.FilterName = FilterName;
    end % End Callback

    function pb_FilterAdd_Callback(~,~)
        import FilterDesign.*
        if sum(strcmp(hdl.data.FilterName,hdl.data.FilterList))>0
            errordlg('Filter name already exists in filter listbox.');
        else
            if hdl.data.iFilterType == 1 % Notch/BandPass
                set(hdl.gui.panelDesignParamLLFirstOrder,'visible','off');
                set(hdl.gui.panelDesignParamLLSecondOrder,'visible','off');
                set(hdl.gui.panelDesignParamNotch,'visible','on');
            elseif hdl.data.iFilterType == 2 % Lead Lag
                set(hdl.gui.panelDesignParamNotch,'visible','off');
                if hdl.data.FilterOrder == 1
                    set(hdl.gui.panelDesignParamLLSecondOrder,'visible','off');
                    set(hdl.gui.panelDesignParamLLFirstOrder,'visible','on');
                    hdl.data.iMaxPhase = get(hdl.gui.panelDesignParamLLFirstOrderCBMaxPhase,'value');
                elseif hdl.data.FilterOrder == 2
                    set(hdl.gui.panelDesignParamLLFirstOrder,'visible','off');
                    set(hdl.gui.panelDesignParamLLSecondOrder,'visible','on');
                end
            end
            
            FilterList = get(hdl.gui.panelFiltersListBox,'string');
            
            nFilters = length(FilterList);
            
            LLSecondOrderOption = get(get(hdl.gui.panelDesignParamLLSecondOrderUIBGroup,'SelectedObject'),'String');
            hdl.data.Filter(nFilters+1).LLSecondOrderOption = LLSecondOrderOption;
            
            hdl.data.Filter(nFilters+1).Name = hdl.data.FilterName;
            
            hdl.data.Filter(nFilters+1).Type = hdl.data.selFilterType;
            hdl.data.Filter(nFilters+1).Order= hdl.data.FilterOrder;
            hdl.data.FilterList{nFilters+1}  = hdl.data.FilterName;
            
            
            set(hdl.gui.panelFiltersListBox,'string',hdl.data.FilterList);
            set(hdl.gui.panelFiltersListBox,'value',nFilters+1);
            
            set(hdl.gui.panelFiltersPMList,'string',hdl.data.FilterList);
            set(hdl.gui.panelFiltersPMList,'value',nFilters+1);
            
            [hdl] = initFilter(hdl);
            
            [hdl] = getFilterDpVals(hdl);
            [hdl] = setFilterDpVals(hdl);
            [hdl] = plotFilter(hdl);
        end
    end

    function pb_FilterDelete_Callback(~,~)
        import FilterDesign.*
        iFilterList = get(hdl.gui.panelFiltersListBox,'value');
        
        if ~isempty(hdl.data.FilterList)
            % Delete filters
            hdl.data.Filter(iFilterList) = [];
            hdl.data.FilterList(iFilterList) = [];
        end
        
        nFilterList = length(hdl.data.FilterList);
        
        if length(iFilterList)==1
            if iFilterList > nFilterList
                iFilterList = nFilterList;
            end
            
            if iFilterList == 0
                iFilterList = 1;
            end
        else
            iFilterList = 1;
        end
        
        % Update listbox
        set(hdl.gui.panelFiltersListBox,'value',iFilterList);
        set(hdl.gui.panelFiltersListBox,'string',hdl.data.FilterList);
        
        set(hdl.gui.panelFiltersPMList,'value',iFilterList);
        
        if ~isempty(hdl.data.FilterList)
            set(hdl.gui.panelFiltersPMList,'string',hdl.data.FilterList);
        else
            set(hdl.gui.panelFiltersPMList,'string',{''});
        end
        
        
        if nFilterList == 0
            [hdl] = clearPlotAxes(hdl);
            [hdl] = initFilter(hdl);
            [hdl] = getFilterDpVals(hdl);
            [hdl] = setFilterDpVals(hdl);
        else
            [hdl] = setFilterDpVals(hdl);
            [hdl] = plotFilter(hdl);
        end
        
    end

    function et_getDpVals_Callback(~,~)
        import FilterDesign.*
        [hdl] = getFilterDpVals(hdl);
        [hdl] = setFilterDpVals(hdl);
        [hdl] = plotFilter(hdl);
    end


    function lb_FilterListBox_Callback(~,~)
        import FilterDesign.*
        selFilter = get(hdl.gui.panelFiltersListBox,'value');
        if length(selFilter)==1
            set(hdl.gui.panelFiltersPMList,'value',selFilter);
       
            [hdl] = setFilterDpVals(hdl);
            
            set(hdl.gui.panelFiltersCBFilterInfo,'enable','on');
        else
            set(hdl.gui.panelFiltersCBFilterInfo,'enable','off');
        end
        [hdl] = getFilterPanel(hdl);
        [hdl] = plotFilter(hdl);
    end

    function pm_FilterListBox_Callback(~,~)
        import FilterDesign.*
        [hdl] = setFilterDpVals(hdl);
        [hdl] = plotFilter(hdl);
        [hdl] = getFilterPanel(hdl);
    end

    function sl_Sliders_Callback(~,~)
        import FilterDesign.*
        [hdl] = updateSliderDpVals(hdl);
        [hdl] = setFilterDpVals(hdl);
        [hdl] = plotFilter(hdl);
    end

    function etDpMinMax_CallBack(~,~)
        import FilterDesign.*
        [hdl] = updateDpMinMax(hdl);
        [hdl] = setFilterDpVals(hdl);
    end

    function pb_PlotFilter_CallBack(~,~)
        import FilterDesign.*
        [hdl] = plotFilter(hdl);
    end

    function pb_ExportFilter_CallBack(~,~)
        import FilterDesign.*
        [hdl] = exportFilter(hdl);
    end

    function et_AddPts_CallBack(~,~)
        import FilterDesign.*
        [hdl] = plotFilter(hdl);
    end

    function cb_MaxPhase_CallBack(~,~)
        import FilterDesign.*
        hdl.data.iMaxPhase = get(hdl.gui.panelDesignParamLLFirstOrderCBMaxPhase,'value');
        if hdl.data.iMaxPhase == 1
            set(hdl.gui.panelDesignParamLLFirstOrderSlMinDpGain,'Enable','off');
            set(hdl.gui.panelDesignParamLLFirstOrderSlMaxDpGain,'Enable','off');
            set(hdl.gui.panelDesignParamLLFirstOrderSlDpGain,'Enable','off');
            set(hdl.gui.panelDesignParamLLFirstOrderStGain,'Enable','off');
            set(hdl.gui.panelDesignParamLLFirstOrderEtDpGain,'Enable','off');
        else
            set(hdl.gui.panelDesignParamLLFirstOrderSlMinDpGain,'Enable','on');
            set(hdl.gui.panelDesignParamLLFirstOrderSlMaxDpGain,'Enable','on');
            set(hdl.gui.panelDesignParamLLFirstOrderSlDpGain,'Enable','on');
            set(hdl.gui.panelDesignParamLLFirstOrderStGain,'Enable','on');
            set(hdl.gui.panelDesignParamLLFirstOrderEtDpGain,'Enable','on');
        end
        
        iFilter    = get(hdl.gui.panelFiltersPMList,'value');

        PMList = get(hdl.gui.panelFiltersPMList,'string');

        if ~isempty(PMList{1})
            hdl.data.Filter(iFilter).iMaxPhase = hdl.data.iMaxPhase;
            [hdl] = plotFilter(hdl);
        end
    end

    function selcb_LLSecondOrderUIBGroup(~,eventdata)
        import FilterDesign.*
        option = get(eventdata.NewValue,'String');
        if strcmp(option,'Specify Freq @ Max Gain')
            set(hdl.gui.panelDesignParamLLSecondOrderStDpFreqGMax,'Enable','on');
            set(hdl.gui.panelDesignParamLLSecondOrderEtDpFreqGMax,'Enable','on');
            set(hdl.gui.panelDesignParamLLSecondOrderSlDpFreqGMax,'Enable','on');
            set(hdl.gui.panelDesignParamLLSecondOrderSlMinDpFreqGMax,'Enable','on');
            set(hdl.gui.panelDesignParamLLSecondOrderSlMaxDpFreqGMax,'Enable','on');
        else
            set(hdl.gui.panelDesignParamLLSecondOrderStDpFreqGMax,'Enable','off');
            set(hdl.gui.panelDesignParamLLSecondOrderEtDpFreqGMax,'Enable','off');
            set(hdl.gui.panelDesignParamLLSecondOrderSlDpFreqGMax,'Enable','off');
            set(hdl.gui.panelDesignParamLLSecondOrderSlMinDpFreqGMax,'Enable','off');
            set(hdl.gui.panelDesignParamLLSecondOrderSlMaxDpFreqGMax,'Enable','off');
        end
        
        iFilter    = get(hdl.gui.panelFiltersPMList,'value');

        PMList = get(hdl.gui.panelFiltersPMList,'string');
        
        if ~isempty(PMList{1})
            hdl.data.Filter(iFilter).LLSecondOrderOption = option;
            [hdl] = plotFilter(hdl);
        end
    end

    function Pm_FreqUnits_CallBack(~,~)
        import FilterDesign.*
        Units = get(hdl.gui.panelFiltersPmFreqUnits,'String');
        iVal  = get(hdl.gui.panelFiltersPmFreqUnits,'Value');
        hdl.data.FreqUnits = Units{iVal};
        
        hdl  = setStringUnits(hdl);
        [hdl] = plotFilter(hdl);
    end

    function Pm_PlotType_CallBack(~,~)
        import FilterDesign.*
        plotTypes = get(hdl.gui.panelFiltersPmPlotType,'String');
        iVal  = get(hdl.gui.panelFiltersPmPlotType,'Value');
        plotType = plotTypes{iVal};
        
        if strcmp(plotType,'Bode')       
            set(hdl.gui.panelPlotPZMap,'visible','off');
            set(hdl.gui.panelPlotNichols,'visible','off');
            set(hdl.gui.panelPlotBode,'visible','on');
            
            set(hdl.gui.panelFiltersStGainLim,'visible','on');
            set(hdl.gui.panelFiltersEtGainLim,'visible','on');
            set(hdl.gui.panelFiltersStPhaseLim,'visible','on');
            set(hdl.gui.panelFiltersEtPhaseLim,'visible','on');
            set(hdl.gui.panelFiltersStFreqMax,'visible','off');
            set(hdl.gui.panelFiltersEtFreqMax,'visible','off');
        elseif strcmp(plotType,'Nichols')
            set(hdl.gui.panelPlotPZMap,'visible','off');
            set(hdl.gui.panelPlotBode,'visible','off');
            set(hdl.gui.panelPlotNichols,'visible','on'); 
            
            set(hdl.gui.panelFiltersStGainLim,'visible','on');
            set(hdl.gui.panelFiltersEtGainLim,'visible','on');
            set(hdl.gui.panelFiltersStPhaseLim,'visible','on');
            set(hdl.gui.panelFiltersEtPhaseLim,'visible','on');
            set(hdl.gui.panelFiltersStFreqMax,'visible','off');
            set(hdl.gui.panelFiltersEtFreqMax,'visible','off');
        elseif strcmp(plotType,'P-Z Map')
            set(hdl.gui.panelPlotBode,'visible','off');
            set(hdl.gui.panelPlotNichols,'visible','off'); 
            set(hdl.gui.panelPlotPZMap,'visible','on');
            
            set(hdl.gui.panelFiltersStGainLim,'visible','off');
            set(hdl.gui.panelFiltersEtGainLim,'visible','off');
            set(hdl.gui.panelFiltersStPhaseLim,'visible','off');
            set(hdl.gui.panelFiltersEtPhaseLim,'visible','off');
            set(hdl.gui.panelFiltersStFreqMax,'visible','on');
            set(hdl.gui.panelFiltersEtFreqMax,'visible','on');
        end
    end

    function cb_FilterInfo_CallBack(~,~)
        import FilterDesign.*
        PMList = get(hdl.gui.panelFiltersPMList,'string');
        
        if ~isempty(PMList{1})
            hdl.data.FilterInfo = get(hdl.gui.panelFiltersCBFilterInfo,'value');
            [hdl] = plotFilter(hdl);
        end
    end
end