classdef ConfigBuilder < handle
    %% Public properties - Graphics Handles
    properties (Transient = true)
        Parent
        LabelTextBoxH
        LabelEditBoxH
        ToolRibbionContainer
        MainInputContainer
        ModelTextBoxH
        ModelEditBoxH
        ModelBrowseButtonH
        ModelConstantsTextBoxH
        ModelConstantsEditBoxH
        ModelConstantsBrowseButtonH
        MassPropTextBoxH
        MassPropEditBoxH
        MassPropBrowseButtonH
        MassPropCreateButtonH
        TrimDefTextBoxH
        TrimDefEditBoxH
        TrimDefBrowseButtonH
        TrimDefCreateButtonH
        LinDefTextBoxH
        LinDefEditBoxH
        LinDefBrowseButtonH
        LinDefCreateButtonH
        
        SaveButtonContainer
        LoadButtonContainer
    end % Public properties
  
    %% Public properties - Data Storage
    properties
        LabelString
        ModelString
        ModelConstantsString
        MassPropertiesString
        TrimDefString
        LinDefString
        
        StartDirectory
        
        ModelConstantState = 'off'
    end % Public properties
        
    %% Read-only properties
    properties ( GetAccess = public, SetAccess = private )
        
    end % Read-only properties
    
    %% Hidden Properties
    properties (Hidden = true)
    end % Hidden properties

    %% Dependant properties
    properties (Dependent = true, SetAccess = private)
    
    end % Dependant properties
    
    %% Constant properties
    properties (Constant) 
        
    end % Constant properties  
    
    %% Events
    events
        LoadConfiguration
    end % Events
    
    %% Methods - Constructor
    methods      
        function obj = ConfigBuilder(parent)  
            switch nargin 
                case 0
                    % Do nothing
                case 1
                   createView(obj,parent); 
            end
        end % ConfigBuilder
    end % ControlDesignGUI

    %% Methods - Property Access
    methods
          
    end % Property access methods
    
    %% Methods - View
    methods
        
        function createView(obj,parent)  
            switch nargin
                case 1
                    obj.Parent = figure('Menubar','none',...   
                        'Toolbar','none',...
                        'MenuBar','none',...
                        'NumberTitle','off',...
                        'HandleVisibility', 'on',...
                        'Visible','on'); 
                case 2
                    obj.Parent = parent;
                                  
            end
            set(obj.Parent,'ResizeFcn',@obj.reSize);
            
            position = getpixelposition(obj.Parent); 
            
            this_dir = fileparts( mfilename( 'fullpath' ) );
            icon_dir = fullfile( this_dir,'..','..','Resources' );

                        
    %% Create Main Input Section  
%     obj.MainInputContainer = uicontainer('Parent',obj.Parent,...
%                                     'Units','Pixels',...
%                                     'Position',[1,1,position(3),position(4) - 80]);
    obj.MainInputContainer = uicontainer('Parent',obj.Parent,...
                                    'Units','Pixels',...
                                    'Position',[1,1,position(3),position(4)]);
            ftSize = 10;
            mainContPos = getpixelposition(obj.MainInputContainer); 
            obj.LabelTextBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','text',...
                'FontSize',ftSize,...
                'HorizontalAlignment','left',...%'FontName','Calibri',...
                'String','Configuration Label:',...
                'Units','Pixels',...
                'Position',[ 1 , mainContPos(4) - 30 , 120 , 20 ]);
            obj.LabelEditBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','edit',...
                'FontSize',ftSize,...
                'String',obj.LabelString,...
                'BackgroundColor',[ 1 , 1 , 1 ],...
                'Units','Pixels',...
                'Position',[ 120 , mainContPos(4) - 30 , mainContPos(3) - 280 , 20 ],...
                'Callback',@obj.labeleditbox_CB);
                        
            
            obj.ModelTextBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','text',...
                'String','Simulink Model:',...
                'FontSize',ftSize,...
                'HorizontalAlignment','left',...
                'Units','Pixels',...
                'Position',[ 1 , mainContPos(4) - 60 , 120 , 20 ]);
            obj.ModelEditBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','edit',...
                'FontSize',ftSize,...
                'String',obj.ModelString,...
                'BackgroundColor',[ 1 , 1 , 1 ],...
                'Units','Pixels',...
                'Position',[ 120 , mainContPos(4) - 60 , mainContPos(3) - 280 , 20 ],...
                'Callback',@obj.modeleditbox_CB);
            obj.ModelBrowseButtonH= uicontrol(...
                'Parent',obj.Parent,...
                'Style','push',...
                'String','Browse',...
                'Units','Pixels',...
                'Position',[ mainContPos(3) - 155 , mainContPos(4) - 60 , 70 , 20 ],...
                'Callback',@obj.modelbrowsebutton_CB);
            
            obj.ModelConstantsTextBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','check',...
                'FontSize',ftSize,...
                'HorizontalAlignment','left',...
                'String','Use Model Constants File:',...
                'Units','Pixels',...
                'Position',[ 1 , mainContPos(4) - 90 , 120 , 20 ],...
                'Callback',@obj.useModelConstants_CB);
            obj.ModelConstantsEditBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','edit',...
                'FontSize',ftSize,...
                'String',obj.ModelConstantsString,...
                'BackgroundColor',[ 1 , 1 , 1 ],...
                'Units','Pixels',...
                'Position',[ 120 , mainContPos(4) - 90 , mainContPos(3) - 280 , 20 ],...
                'Callback',@obj.modelconstantseditbox_CB);
            obj.ModelConstantsBrowseButtonH= uicontrol(...
                'Parent',obj.Parent,...
                'Style','push',...
                'String','Browse',...
                'Units','Pixels',...
                'Position',[ mainContPos(3) - 155 , mainContPos(4) - 90 , 70 , 20 ],...
                'Callback',@obj.modelconstantsbrowsebutton_CB);
            
            obj.MassPropTextBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','text',...
                'FontSize',ftSize,...
                'HorizontalAlignment','left',...
                'String','Mass Properties Database:',...
                'Units','Pixels',...
                'Position',[ 1 , mainContPos(4) - 120 , 120 , 20 ]);
            obj.MassPropEditBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','edit',...
                'FontSize',ftSize,...
                'String',obj.MassPropertiesString,...
                'BackgroundColor',[ 1 , 1 , 1 ],...
                'Units','Pixels',...
                'Position',[ 120 , mainContPos(4) - 120 , mainContPos(3) - 280 , 20 ],...
                'Callback',@obj.masspropeditbox_CB);
            obj.MassPropBrowseButtonH= uicontrol(...
                'Parent',obj.Parent,...
                'Style','push',...
                'String','Browse',...
                'Units','Pixels',...
                'Position',[ mainContPos(3) - 155 , mainContPos(4) - 120 , 70 , 20 ],...
                'Callback',@obj.masspropbrowsebutton_CB);
            obj.MassPropCreateButtonH= uicontrol(...
                'Parent',obj.Parent,...
                'Style','push',...
                'String','Create',...
                'Units','Pixels',...
                'Enable','off',...
                'Position',[ mainContPos(3) - 80 , mainContPos(4) - 120 , 70 , 20 ],...
                'Callback',@obj.masspropcreatebutton_CB);
            
            obj.TrimDefTextBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','text',...
                'FontSize',ftSize,...
                'HorizontalAlignment','left',...
                'String','Trim Definition Database:',...
                'Units','Pixels',...
                'Position',[ 1 , mainContPos(4) - 150 , 120 , 20 ]);
            obj.TrimDefEditBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','edit',...
                'FontSize',ftSize,...
                'String',obj.TrimDefString,...
                'BackgroundColor',[ 1 , 1 , 1 ],...
                'Units','Pixels',...
                'Position',[ 120 , mainContPos(4) - 150 , mainContPos(3) - 280 , 20 ],...
                'Callback',@obj.trimdefeditbox_CB);
            obj.TrimDefBrowseButtonH= uicontrol(...
                'Parent',obj.Parent,...
                'Style','push',...
                'String','Browse',...
                'Units','Pixels',...
                'Position',[ mainContPos(3) - 155 , mainContPos(4) - 150 , 70 , 20 ],...
                'Callback',@obj.trimdefbrowsebutton_CB);
            obj.TrimDefCreateButtonH= uicontrol(...
                'Parent',obj.Parent,...
                'Style','push',...
                'String','Create',...
                'Units','Pixels',...
                'Enable','off',...
                'Position',[ mainContPos(3) - 80 , mainContPos(4) - 150 , 70 , 20 ],...
                'Callback',@obj.trimdefcreatebutton_CB);
            
            obj.LinDefTextBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','text',...
                'FontSize',ftSize,...
                'HorizontalAlignment','left',...
                'String','Linear Definition Database:',...
                'Units','Pixels',...
                'Position',[ 1 , mainContPos(4) - 180 , 120 , 20 ]);
            obj.LinDefEditBoxH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','edit',...
                'FontSize',ftSize,...
                'String',obj.LinDefString,...
                'BackgroundColor',[ 1 , 1 , 1 ],...
                'Units','Pixels',...
                'Position',[ 120 , mainContPos(4) - 180 , mainContPos(3) - 280 , 20 ],...
                'Callback',@obj.lindefeditbox_CB);
            obj.LinDefBrowseButtonH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','push',...
                'String','Browse',...
                'Units','Pixels',...
                'Position',[ mainContPos(3) - 155 , mainContPos(4) - 180 , 70 , 20 ],...
                'Callback',@obj.lindefbrowsebutton_CB);
            obj.LinDefCreateButtonH= uicontrol(...
                'Parent',obj.MainInputContainer,...
                'Style','push',...
                'String','Create',...
                'Units','Pixels',...
                'Enable','off',...
                'Position',[ mainContPos(3) - 190 , mainContPos(4) - 250 , 70 , 20 ],...
                'Callback',@obj.lindefcreatebutton_CB);  
            
            % Add Buttons
            % Save Button             
            saveJButton = javaObjectEDT('com.mathworks.mwswing.MJButton');
            saveJButton.setText('Save');        
            saveJButtonH = handle(saveJButton,'CallbackProperties');
            set(saveJButtonH, 'ActionPerformedCallback',@obj.saveConfig_CB)
            myIcon = fullfile(icon_dir,'Save_Load_24.png');
            saveJButton.setIcon(javax.swing.ImageIcon(myIcon));
            saveJButton.setToolTipText('Save and Load');
            saveJButton.setFlyOverAppearance(true);
            saveJButton.setBorder([]);
            saveJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            saveJButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            saveJButton.setMargin(java.awt.Insets(0, 0, 0, 0));
            [ ~ , obj.SaveButtonContainer] = javacomponent(saveJButton, [ 10 , mainContPos(4) - 330 , 35 , 60 ], obj.MainInputContainer);

            
            % New Button             
            newJButton = javaObjectEDT('com.mathworks.mwswing.MJButton');
            newJButton.setText('Clear');        
            newJButtonH = handle(newJButton,'CallbackProperties');
            set(newJButtonH, 'ActionPerformedCallback',@obj.newConfig_CB)
            myIcon = fullfile(icon_dir,'Clean_24.png');
            newJButton.setIcon(javax.swing.ImageIcon(myIcon));
            newJButton.setToolTipText('Clear fields');
            %newJButton.setIconTextGap(0);
            newJButton.setFlyOverAppearance(true);
            newJButton.setBorder([]);
            newJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            newJButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            newJButton.setMargin(java.awt.Insets(0, 0, 0, 0));
            [ ~ , obj.LoadButtonContainer] = javacomponent(newJButton, [ 45 , mainContPos(4) - 330 , 35 , 60 ], obj.MainInputContainer);
            
            update(obj);
            reSize( obj , [] , [] );
        end % createView

    end
   
    %% Methods - Ordinary
    methods 
        function config = createConfigObj( obj )
            % Create a Configuration Object
            config = lacm.Configuration(obj.ModelString,...
                                                obj.ModelConstantsString,...
                                                obj.TrimDefString,...
                                                obj.LinDefString,...
                                                obj.MassPropertiesString,...
                                                obj.LabelString);
        end % createConfigObj

    end % Ordinary Methods
    
    %% Methods - Callbacks
    methods (Access = protected) 
        
        function newConfig_CB( obj , ~ , ~ )
            obj.LabelString = '';
            obj.ModelString = '';
            obj.ModelConstantsString = '';
            obj.MassPropertiesString = '';
            obj.TrimDefString = '';
            obj.LinDefString = '';
            
            update(obj);
        end % newConfig_CB

        function saveConfig_CB( obj , ~ , ~)
            config = createConfigObj( obj ); 
            notify(obj,'LoadConfiguration',UserInterface.StabilityControl.LoadConfigEventData(config));% Just added
            uisave('config','Configuration');
        end % saveConfig_CB
        
        function loadConfig_CB( obj , ~ , ~)        
            config = createConfigObj( obj );
            notify(obj,'LoadConfiguration',UserInterface.StabilityControl.LoadConfigEventData(config));  
        end % loadConfig_CB
        
        function labeleditbox_CB( obj , hobj , ~ )
            obj.LabelString = get(hobj,'String'); 
            obj.update;  
        end % labeleditbox_CB
        
        function modeleditbox_CB( obj , hobj , ~ )
            obj.ModelString = get(hobj,'String'); 
            obj.update;  
        end % modeleditbox_CB
        
        function modelbrowsebutton_CB( obj , ~ , ~ )
            [FileName,PathName,~] = uigetfile({'*.mdl'},'Select a Model File',obj.StartDirectory);
            if isequal(FileName,0)
                return;
            end
            obj.StartDirectory = PathName;
            obj.ModelString = fullfile(PathName,FileName); 
            obj.update;  
        end % modelbrowsebutton_CB
        
        function modelconstantseditbox_CB( obj , hobj , ~ )
            obj.ModelConstantsString = get(hobj,'String'); 
            obj.update;  
        end % modelconstantseditbox_CB
        
        function modelconstantsbrowsebutton_CB( obj , ~ , ~ )
            [FileName,PathName,~] = uigetfile({'*.mat'},'Select a Model File',obj.StartDirectory);
            if isequal(FileName,0)
                return;
            end
            obj.StartDirectory = PathName;
            obj.ModelConstantsString = fullfile(PathName,FileName); 
            obj.update;  
        end % modelconstantsbrowsebutton_CB
        
        function masspropeditbox_CB( obj , hobj , ~ )
            obj.MassPropertiesString = get(hobj,'String'); 
            obj.update;  
        end % masspropeditbox_CB
        
        function masspropbrowsebutton_CB( obj , ~ , ~ )
            [FileName,PathName,~] = uigetfile({'*.txt'},'Select a MassProperties File',obj.StartDirectory);
            if isequal(FileName,0)
                return;
            end
            obj.StartDirectory = PathName;
            obj.MassPropertiesString = fullfile(PathName,FileName); 
            obj.update;  
        end % masspropbrowsebutton_CB
        
        function masspropcreatebutton_CB( obj , ~ , ~ )
            obj.update;  
        end % masspropcreatebutton_CB    
        
        function trimdefeditbox_CB( obj , hobj , ~ )
            obj.TrimDefString = get(hobj,'String'); 
            obj.update;  
        end % trimdefeditbox_CB
        
        function trimdefbrowsebutton_CB( obj , ~ , ~ )
            [FileName,PathName,~] = uigetfile({'*.txt'},'Select a Trim Definition File',obj.StartDirectory);
            if isequal(FileName,0)
                return;
            end
            obj.StartDirectory = PathName;
            obj.TrimDefString = fullfile(PathName,FileName); 
            obj.update;  
        end % trimdefbrowsebutton_CB
        
        function trimdefcreatebutton_CB( obj , ~ , ~ )
            obj.update;  
        end % trimdefcreatebutton_CB    
        
        function lindefeditbox_CB( obj , hobj , ~ )
            obj.LinDefString = get(hobj,'String'); 
            obj.update;  
        end % lindefeditbox_CB
        
        function lindefbrowsebutton_CB( obj , ~ , ~ )
            [FileName,PathName,~] = uigetfile({'*.txt'},'Select a Linear Model Definition File',obj.StartDirectory);
            if isequal(FileName,0)
                return;
            end
            obj.StartDirectory = PathName;
            obj.LinDefString = fullfile(PathName,FileName); 
            obj.update;  
        end % lindefbrowsebutton_CB
        
        function lindefcreatebutton_CB( obj , ~ , ~ )
            obj.update;  
        end % lindefcreatebutton_CB
        
        function useModelConstants_CB( obj , hobj , ~ )
            state = get(hobj,'Value');
            if state
                obj.ModelConstantState = 'on';
            else
                obj.ModelConstantState = 'off'; 
            end
            obj.update;  
        end % useModelConstants_CB
        
        
    end
    
    %% Methods - Protected
    methods (Access = protected) 
        
        function update( obj, ~ , ~ ) 
            set(obj.LabelEditBoxH,'String',obj.LabelString);
            set(obj.ModelEditBoxH,'String',obj.ModelString);
            set(obj.ModelConstantsEditBoxH,'String',obj.ModelConstantsString);
            set(obj.MassPropEditBoxH,'String',obj.MassPropertiesString);
            set(obj.TrimDefEditBoxH,'String',obj.TrimDefString);
            set(obj.LinDefEditBoxH,'String',obj.LinDefString); 
            
            set(obj.ModelConstantsEditBoxH,'Enable',obj.ModelConstantState);
            set(obj.ModelConstantsBrowseButtonH,'Enable',obj.ModelConstantState);
        end % update
         
        function reSize( obj , ~ , ~ )
            
            % get figure position
            position = getpixelposition(obj.Parent);
       
%             set(obj.ToolRibbionContainer,'Units','Pixels',...
%                 'Position',[1,position(4)-80,position(3),80]);
            set(obj.MainInputContainer,'Units','Pixels',...
                                    'Position',[1,1,position(3),position(4)]);
                                
            mainContPos = getpixelposition(obj.MainInputContainer);                      
            set(obj.LabelTextBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 30 , 220 , 20 ]);
            set(obj.LabelEditBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 50 , mainContPos(3) - 280 , 20 ]);
                        
            
            set(obj.ModelTextBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 70 , 220 , 20 ]);
            set(obj.ModelEditBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 90 , mainContPos(3) - 280 , 20 ]);
            set(obj.ModelBrowseButtonH,'Units','Pixels',...
                'Position',[ mainContPos(3) - 265 , mainContPos(4) - 90 , 70 , 20 ]);
            
            set(obj.ModelConstantsTextBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 110 , 220 , 20 ]);
            set(obj.ModelConstantsEditBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 130 , mainContPos(3) - 280 , 20 ]);
            set(obj.ModelConstantsBrowseButtonH,'Units','Pixels',...
                'Position',[ mainContPos(3) - 265 , mainContPos(4) - 130 , 70 , 20 ]);
            
            set(obj.MassPropTextBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 150 , 220 , 20 ]);
            set(obj.MassPropEditBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 170 , mainContPos(3) - 280 , 20 ]);
            set(obj.MassPropBrowseButtonH,'Units','Pixels',...
                'Position',[ mainContPos(3) - 265 , mainContPos(4) - 170 , 70 , 20 ]);
            set(obj.MassPropCreateButtonH,'Units','Pixels',...
                'Position',[ mainContPos(3) - 190 , mainContPos(4) - 170 , 70 , 20 ]);
            
            set(obj.TrimDefTextBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 190 , 220 , 20 ]);
            set(obj.TrimDefEditBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 210 , mainContPos(3) - 280 , 20 ]);
            set(obj.TrimDefBrowseButtonH,'Units','Pixels',...
                'Position',[ mainContPos(3) - 265 , mainContPos(4) - 210 , 70 , 20 ],...
                'Callback',@obj.trimdefbrowsebutton_CB);
            set(obj.TrimDefCreateButtonH,'Units','Pixels',...
                'Position',[ mainContPos(3) - 190 , mainContPos(4) - 210 , 70 , 20 ]);
            
            set(obj.LinDefTextBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 230 , 220 , 20 ]);
            set(obj.LinDefEditBoxH,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 250 , mainContPos(3) - 280 , 20 ],...
                'Callback',@obj.lindefeditbox_CB);
            set(obj.LinDefBrowseButtonH,'Units','Pixels',...
                'Position',[ mainContPos(3) - 265 , mainContPos(4) - 250 , 70 , 20 ]);
            set(obj.LinDefCreateButtonH,'Units','Pixels',...
                'Position',[ mainContPos(3) - 190 , mainContPos(4) - 250 , 70 , 20 ]);           

            set(obj.SaveButtonContainer,'Units','Pixels',...
                'Position',[ 10 , mainContPos(4) - 330 , 35 , 60 ]);
            set(obj.LoadButtonContainer,'Units','Pixels',...
                'Position',[ 45 , mainContPos(4) - 330 , 35 , 60 ]);  
                                
        end % reSize
        
        
    end
    
    %% Methods - Private
    methods (Access = private) 
        

    end
    
    
    %% Method - Static
    methods ( Static )
        
        
    end
        
end
